1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [3]:
import numpy as np
m = np.arange(12).reshape((3,4))
print(m)

print("Mean total - ", np.mean(m))
print("Mean for each row")
for idx, row in enumerate(m):
    print(idx, "-", np.mean(row))

print("Mean for each column")
for idx, column in enumerate(np.transpose(m)):
    print(idx, "-", np.mean(column))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mean total -  5.5
Mean for each row
0 - 1.5
1 - 5.5
2 - 9.5
Mean for each column
0 - 4.0
1 - 5.0
2 - 6.0
3 - 7.0


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [8]:
import numpy as np
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
print("Using the function outer in numpy")
print(np.outer(u,v))
print("Using a nested for loop or a list comprehension")
print(np.array([(i*j) for i in v for j in u]).reshape(4,4).T)
print("Using numpy broadcasting operations")
print(np.ones((4,4))*v*(np.ones((4,4))*u).T)

Using the function outer in numpy
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
Using a nested for loop or a list comprehension
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
Using numpy broadcasting operations
[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [12]:
m = np.reshape(np.arange(0, 6, 0.1), (6, 10))
print(m)

for i, row in enumerate(m):
    for j, number in enumerate(row):
        if number % 1 < 0.4:
            m[i, j]=0
print(m)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]
[[0.  0.  0.  0.  0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.  0.  0.  1.4 1.5 1.6 1.7 1.8 1.9]
 [0.  0.  0.  0.  2.4 2.5 2.6 2.7 2.8 2.9]
 [0.  0.  0.  0.  3.4 3.5 3.6 3.7 3.8 3.9]
 [0.  0.  0.  0.  4.4 4.5 4.6 4.7 4.8 4.9]
 [0.  0.  0.  0.  5.4 5.5 5.6 5.7 5.8 5.9]]


4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [26]:
import math

m = np.linspace(0,2*math.pi, 100)
print(m)

print("Every 10th element:\n", m[0:100:10])

print("Reversed array:\n", m[::-1])

print("Extract elements:\n", np.array([i for i in m if abs(math.sin(i)-math.cos(i))<0.1]))

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [25]:
matrix = np.array([x*y for x in range(1, 11) for y in range(1, 11)]).reshape(10, 10)
print("Find the trace of the matrix\n", matrix)

anti_diag = np.fliplr(matrix)
print("Extract the anti-diagonal matrix\n", anti_diag)

print("Extract the diagonal offset by 1 upwards\n", np.diag(matrix, k=1))

Find the trace of the matrix
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
Extract the anti-diagonal matrix
 [[ 10   9   8   7   6   5   4   3   2   1]
 [ 20  18  16  14  12  10   8   6   4   2]
 [ 30  27  24  21  18  15  12   9   6   3]
 [ 40  36  32  28  24  20  16  12   8   4]
 [ 50  45  40  35  30  25  20  15  10   5]
 [ 60  54  48  42  36  30  24  18  12   6]
 [ 70  63  56  49  42  35  28  21  14   7]
 [ 80  72  64  56  48  40  32  24  16   8]
 [ 90  81  72  63  54  45  36  27  18   9]
 [100  90  80  70  60  50  40  30  20  10]]
Extract the diagonal offset by 1 upwards
 [ 2  6 12 20 30 42 56 72 90]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [31]:
distances = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
distances = np.abs(distances - distances[:, np.newaxis])
print("Distances miles\n", distances)

distances_km = distances * 1.61
print("Distances km\n", distances_km)

Distances miles
 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]
Distances km
 [[   0.    318.78  487.83 1184.96 1402.31 1891.75 2374.75 2485.84 3079.93
  3941.28]
 [ 318.78    0.    169.05  866.18 1083.53 1572.97 2055.97 2167.06 2761.15
  3622.5 ]
 [ 487.83  169.05    0.    697.13  914.48 1403.92 1886.92 1998.01 2592.1
  3453.45]
 [1184.96  866.18  697.13    0.    217.35  706.79 1189.79 1300.88 1894.97
  2756.32]
 [1402.31 1083.53  914.48  217.35    0.    489.44  972.44 1083.53 1677.62
  2538.97]
 [1891.75 1572

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)